config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#index'

  resources :users, :cities, :bookings, :charges



  # get 'homes/:id/book' => 'bookings#new', :as => 'new_booking'
  # post 'homes/:id/book' => 'bookings#create'

  resources :homes do
    resources :bookings, :only => [:new, :create]
  end


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :integer          not null, primary key
#  start_date :datetime
#  end_date   :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  home_id    :integer
#

class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :home
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  country    :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :text
#

class City < ActiveRecord::Base
  has_many :homes
end

app/models/home.rb
# == Schema Information
#
# Table name: homes
#
#  id          :integer          not null, primary key
#  city_id     :integer
#  user_id     :integer
#  max_guests  :integer
#  bathrooms   :integer
#  check_in    :time
#  check_out   :time
#  description :text
#  image       :text
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :text
#

class Home < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  has_many :bookings
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :text
#  last_name       :text
#  email           :text
#  dob             :date
#  image           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true, :uniqueness => true

  has_many :homes
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]
    end

    session[:user_id] = nil unless @current_user.present?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find params[:id]
  end

  def new
    @home = Home.find params[:home_id]
    @booking = Booking.new
  end

  def create
    @home = Home.find params[:home_id]
    if @home.present?
      start_year = params[:booking]['start_date(1i)'].to_i
      start_month = params[:booking]['start_date(2i)'].to_i
      start_day = params[:booking]['start_date(3i)'].to_i
      end_year = params[:booking]['end_date(1i)'].to_i
      end_month = params[:booking]['end_date(2i)'].to_i
      end_day = params[:booking]['end_date(3i)'].to_i
      start_date = DateTime.new(start_year, start_month, start_day)
      end_date = DateTime.new(end_year, end_month, end_day)
      bookable = true
      if @home.bookings.any?
        @home.bookings.each do |booking|
          if (start_date..end_date).overlaps?(booking.start_date..booking.end_date)
            flash[:error] = "Not available."
            bookable = false
            puts "unbookable start: #{start_date}, end: #{end_date}. existing start: #{booking.start_date}, existing end: #{booking.end_date}"
          end
        end
      end
      if bookable
        puts "is bookable"
        new_booking = @home.bookings.new(booking_params)
        @current_user.bookings << new_booking if new_booking.valid?
        new_booking.save
        redirect_to new_charge_path
      else
        puts "is not bookable"
        @booking = Booking.new
        render :new
      end
    end
  end

  def edit
    @booking = Booking.find params[:id]
  end

  def update
    booking = Booking.find params[:id]
    booking.update booking_params
    redirect_to booking

  end

  def destroy
    booking = Booking.find params[:id]
    booking.destroy
    redirect_to bookings_path
  end

  private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    redirect_to bookings_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find params[:id]
  end

  def new
    @city = City.new
  end

  def create
    city = City.create city_params
    redirect_to cities_path
  end

  def edit
    @city = City.find params[:id]
  end

  def update
    city = City.find params[:id]
    city.update city_params
    redirect_to city
  end

  def destroy
    city = City.find params[:id]
    city.destroy
    redirect_to cities_path
  end


  private
  def city_params
    params.require(:city).permit(:name, :country, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Home.all
  end

  def show
    @home = Home.find params[:id]
    @bookings = Booking.all
  end

  def new
    @home = Home.new
  end

  def create
    # home = Home.create home_params
    home = @current_user.homes.create home_params # Associates the home to the logged in user
    redirect_to homes_path
  end

  def edit
    @home = Home.find params[:id]
  end

  def update
    home = Home.find params[:id]
    home.update home_params
    redirect_to home
  end

  def destroy
    home = Home.find params[:id]
    home.destroy
    redirect_to homes_path
  end

  private
  def home_params
    params.require(:home).permit(:name, :city_id, :user_id, :max_guests, :bathrooms, :check_in, :check_out, :description, :image, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= form_for [@home, @booking] do |f| %>
  <p class="booking-form">

    <%= f.label :start_date %>
    <%= f.date_select :start_date, :class => 'datepicker' %>
  </p>
  <p class="booking-form">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, :required => true %>
  </p>

  <%= f.submit%>
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
  <h2>Change your booking</h2>

  <%= render :partial => 'form' %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h2>Your Bookings</h2>
  <ul>
    <% @bookings.each do |booking| %>
      <% if booking.user_id == @current_user.id %>
        <%= link_to(booking_path(booking.id)) do %>
          <li class="bookings-index">
            <div class="booking-name">
              <h3><%= booking.home.name %></h3>
              <span class="city-label"><%= booking.home.city.name %></span>
            </div>
            <div class="booking-details">
              <%= booking.start_date.strftime('%A %e %B, %Y') %> - <%= booking.end_date.strftime('%A %e %B, %Y') %>
            </div>
            <%= image_tag booking.home.image, :class => 'booking-index-thumb' %>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h2>Make a booking</h2>

  <%= render :partial => 'form' %>

</div>

app/views/bookings/show.html.erb
<div class="container">
  <h2>Your Booking</h2>
  <%= @booking.start_date.strftime '%A %e %B, %Y' %> -
  <%= @booking.end_date.strftime '%A %e %B, %Y' %>


  <div class="controllers">
    <%= link_to 'Edit booking', edit_booking_path(@booking.id) %>
    <%= link_to 'Delete booking', @booking, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>

  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article class="payment">
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Home away from home"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>

  <p>
    <%= f.label :name, "City" %>
    <%= f.text_field :name, :placeholder => "London", :required => true %>
  </p>
  <p>
    <%= f.label :country %>
    <%= f.text_field :country, :placeholder => "England", :required => true %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.text_field :image, :required => true %>
  </p>

  <%= f.submit %>
<% end %>

app/views/cities/edit.html.erb
<div class="container">
  <h2>Edit <%= @city.name %></h2>

  <%= render :partial => 'form' %>
</div>

app/views/cities/index.html.erb
<div class="container">
  <h2>Home, wherever you are</h2>

  <%= link_to 'Can\'t find your city on the list? Add it here', new_city_path %>


  <div class="cities_display">
    <% @cities.each do |city| %>
      <%= link_to(city_path(city.id)) do %>
        <div class="city_thumb_wrapper">
          <%= image_tag city.image, :class => 'thumb' %>
          <p><%= city.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cities/new.html.erb
<div class="container">
  <h2>Add your city to the list</h2>

  <%= render :partial => 'form' %>
</div>

app/views/cities/show.html.erb
<div class="container">
  <h2><%= @city.name %></h2>
  <h3><%= @city.country %> </h3>


  <div class="homes_display">
    <% @city.homes.each do |home| %>
      <%= link_to(home_path(home.id)) do %>
        <div class="home_thumb_wrapper">
          <%= image_tag home.image, :class => 'thumb' %>
          <p><%= home.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/homes/_form.html.erb
<%= form_for @home do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
  </p>
  <p>
    <%= f.label :max_guests %>
    <%= f.text_field :max_guests, :required => true %>
  </p>
  <p>
    <%= f.label :bathrooms %>
    <%= f.text_field :bathrooms, :required => true %>
  </p>
  <p>
    <%= f.label :check_in %>
    <%= f.text_field :check_in, :required => true %>
  </p>
  <p>
    <%= f.label :check_out %>
    <%= f.text_field :check_out, :required => true %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description, :required => true %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.text_field :image, :required => true %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.text_field :price, :required => true %>
  </p>
  <p class="submit">
    <%= f.label :city_id %>
    <%= f.select :city_id, City.pluck(:name, :id), :prompt => 'Select City', :required => true %>
  </p>

  <%= f.submit%>
<% end %>

app/views/homes/edit.html.erb
<div class="container">
  <h2>Edit <%= @home.name %></h2>

  <%= render :partial => 'form' %>
</div>

app/views/homes/index.html.erb
<div class="container">
  <h2>All Homes</h2>
    <%= link_to 'Add your home', new_home_path, :class => 'addhome' %>
  <ul>
    <% @homes.each do |home| %>
      <%= link_to(home_path(home.id)) do %>
        <li class="home-index">
          <div class="name-price">
            <h3><%= home.name %><h3>
            <span class="city-label">
              <%= home.city.name %>
            </span>
            <br>
            <span class="price">
              $<%= home.price %>
            </span>
          </div>
          <p>
            Max Guests: <%= home.max_guests %>
            <br>
            Bathrooms: <%= home.bathrooms %>
            <br><br>
            <%= home.description %>
          </p>
          <%= image_tag home.image, :class => 'home-index-thumb' %>


        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/homes/new.html.erb
<div class="container">
  <h2>New home</h2>

  <%= render :partial => 'form' %>
</div>

app/views/homes/show.html.erb
<div class="home-header">
  <%= image_tag @home.image, :class => 'feature' %>
  <h2><%= @home.name %></h2>
</div>

<div class="home-show-container">
  <h3><%= @home.city.name %></h3>
  <p>
    <strong>Max guests:</strong> <%= @home.max_guests %><br>
    <strong>Bathrooms:</strong> <%= @home.bathrooms %><br>
    <strong>Check In:</strong> <%= @home.check_in.strftime('%l %M %p') %><br>
    <strong>Check Out:</strong> <%= @home.check_out.strftime('%l %M %p') %><br>
    <%= @home.description %><br>
    <span class="price"><strong>Price:</strong> <%= @home.price %></span><br>
  </p>




  <div class="controllers">
    <% if @current_user.present? == false %>
      <%= link_to 'Login to Book this Home', login_path %>
    <% elsif @current_user.id == @home.user_id %>
      <%= link_to 'Edit home', edit_home_path %>
      <%= link_to 'Delete home', @home, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
    <% else %>
      <%= link_to 'Book this home', "/homes/#{@home.id}/bookings/new" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="main-nav">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Explore Cities', cities_path %>
      <%= link_to 'Explore Homes', homes_path %>
    </div>
    <div class="credentials">
      <% if @current_user.present? %>
        <%= link_to "Your Bookings", bookings_path %>
        <%= link_to "Logout #{@current_user.first_name}", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign In', login_path %>
      <% end %>
    </div>

  </nav>

  <%= yield %>



</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <% content_for :header do %>
    <%= stylesheet_link_tag 'homepage', media: 'all' %>
  <% end %>

  <%= image_tag 'https://images.unsplash.com/photo-1474690455603-a369ec1293f9?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&s=9aedb8702984f67b18a9af4df6f45bc4', :class => 'homefeature' %>

  <div class="homecontainer">
    <h1>Home, wherever you are</h1>


    <%= link_to 'Explore Homes', homes_path, :class => 'landerbutton' %>
    <%= link_to 'Explore Cities', cities_path, :class => 'landerbutton' %>



  </div>
</div>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Log in" %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit 'Sign up' %>




<% end %>